#  port -> 0?? ?? ? ??? ??? ?? ????.
#  0?? ?? ? ??? member-service:0 ???? ??? ??? ?????? ????.
#  ?, ?? ??? ???? ?? ????? ??? ? ?? ???? ID? ??? ?? ?? ????.
server:
  port: 8001

eureka:
  client:
    register-with-eureka: true  #??? ??? ?? ??.
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}}

spring:
  application:
    name: member-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member_service_db?verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    properties:
      format_sql: true

logging:
  level:
    kr.co.memberservice: DEBUG