# port -> 0?? ?? ? ??? ??? ?? ????.
# 0?? ?? ? ??? member-service:0 ???? ??? ??? ?????? ????.
# ?, ?? ??? ???? ?? ????? ??? ? ?? ???? ID? ??? ?? ?? ????.
server:
  port: 0


spring:
  application:
    name: member-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member_service_db?verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    properties:
      format_sql: true

eureka:
  client:
    register-with-eureka: true  # ??? ??? ?? ??.
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}}

