server:
  port: 8787

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false   # euraka? registry? ??? ? ?? ??.
    fetch-registry: false         # registy? ?? ??? ??? ? ?? ??.